### ISSUE TITLE
Documentação de contexto

### ISSUE THREAD

**Issue by adrianansc** [ICEI-PUC-Minas-PMV-ADS/Clube-Campestre#1]
- [x] Introdução
- [x] Problema
- [x] Objetivos
- [x] Justificativa
- [x] Relação com a Extensão Universitária
- [x] Descrição do Parceiro

**Comment by GTadim** [comment]
Faltando correções ortográficas e adição da contribuição para a sociedade @adrianansc

**Comment by GTadim** [comment]
Adicionadas informações restantes por meio do commit https://github.com/ICEI-PUC-Minas-PMV-ADS/Clube-Campestre/commit/37330b4c8205199fa4671b700f9d05884cc46429
