### ISSUE TITLE
[FrontEnd] - Modal Extrato de Pagamentos

### ISSUE THREAD

**Issue by GTadim** [ICEI-PUC-Minas-PMV-ADS/Clube-Campestre#22]
[RF-07]

- [ ] Desenvolver estrutura de tabela do Modal
- [ ] Consumo da rota de Mensalidades

**Comment by rafaelteixeira** [comment]
Gustavo, posso ficar com esse?

**Comment by GTadim** [comment]
A princípio o desenvolvimento dessa tarefa não será mais realizado.
